# clear_screen
# copy_to_clipboard
# show_generated_code
# create_label
# add_field
# class_input_page
# generate_class
# function_input_page
# generate_function
# tuple_input_page
# generate_tuple
# list_input_page
# generate_list
# dict_input_page
# generate_dict
# set_input_page
# Zgenerate_set
# main_menu